[package]
name = "compress-photos"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.2", features = ["jpeg"] }
clap = { version = "4.5.19", features = ["cargo"] }
log = "0.4.22"