[package]
name = "compress-photos"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.2", features = ["jpeg"] }
little_exif = "0.6.2"
clap = { version = "4.5.19", features = ["cargo"] }
log = "0.4.22"
simple_logger = "5.0.0"
even_bigger_s = "1.0.0"
anyhow = "1.0.89"